AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: valorant-match schedule - Function invokes fetching functions

Parameters:
  ScheduleExpression:
    Description: schedule expression for the eventbridge event
    Type: String
    Default: rate(6 hours)
  FetchDailyMatchesQueueUrl:
    Description: SQS queue url publish to
    Type: String

Resources:
  GetMatchListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/
      Description: "invoke fetch-daily-matches function via SQS queue publishing"
      Handler: index.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 180
      Policies:
        - AmazonSQSFullAccess
      Environment:
        Variables:
          FETCH_DAILY_MATCHES_QUEUE_URL: !Ref FetchDailyMatchesQueueUrl
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
