AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: valorant-match-schedule

Parameters:
  ScheduleExpression:
    Description: schedule expression for the eventbridge event
    Type: String
    Default: rate(6 hours)
  MatchListTable:
    Description: DynamoDB table name for match list
    Type: String

Resources:
  RequestsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: requests
      ContentUri: layer/requests/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  GetMatchListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/
      Description: "get valorant match list"
      Handler: index.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 900
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          MATCHLIST_TABLE: !Ref MatchListTable
      Layers:
        - !Ref RequestsLayer
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
