[tools]
aws-sam-cli = "1.142.1"
go = "1.24.1"

[tasks.fmt]
run = "go fmt ./..."

[tasks.lint]
depends = ["fmt"]
run = [
    "go tool staticcheck ./...", "go vet ./...", "go mod tidy"
]

[tasks.test]
depends = ["lint"]
run = [
    "go test -v ./..."
]

[tasks.build]
depends = ["test"]
env = { "GOOS" = "linux", "GOARCH" = "amd64", "CGO_ENABLED" = "0" }
run = [
    "go build -trimpath -tags lambda.norpc -o .build/scrape/bootstrap cmd/scrape/main.go",
    "go build -trimpath -tags lambda.norpc -o .build/register/bootstrap cmd/register/main.go",
    "go build -trimpath -tags lambda.norpc -o .build/update-calendars/bootstrap cmd/update-calendars/main.go",
]

[tasks.deploy_dev]
depends = ["build"]
run = [
    "sam deploy --config-file samconfig.toml --config-env dev --no-confirm-changeset",
]

[tasks.run_dev]
env = { "AWS_DEFAULT_REGION" = "us-east-1" }
run = [
    "aws stepfunctions start-execution --state-machine-arn $(aws stepfunctions list-state-machines --query 'stateMachines[?name==`dev-vms-scrape-matches`].stateMachineArn' --output text) --name $(date +%Y%m%d-%H%M%S)"
]
