AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"
Description: valorant-match-schedule

Parameters:
  APIEndpointDomainName:
    Description: Domain name of API endpoint URL of dima (matches API)
    Type: String
    AllowedPattern: ^([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\.)+[a-zA-Z]{2,}$
    ConstraintDescription: should be appropriate domain format
  GoogleServiceAccountId:
    Type: String
  CalendarIdApac:
    Type: String
  CalendarIdBrLatam:
    Type: String
  CalendarIdEastAsia:
    Type: String
  CalendarIdEmea:
    Type: String
  CalendarIdNa:
    Type: String
  CalendarIdInternational:
    Type: String
  ScheduleExpression:
    Description: schedule expression for the eventbridge event
    Type: String
    Default: rate(3 hours)
  DaysToGet:
    Description: days to get match info starting from today
    Type: Number
    Default: 30
  DaysToRetainLogs:
    Description: days to retain logs in CloudWatch
    Type: Number
    Default: 30

Resources:
  GoogleAuthLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: google-auth
      ContentUri: add-gcal-event/layer/google-auth/
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

  GoogleApiPythonClientLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: google-api-python-client
      ContentUri: add-gcal-event/layer/google-api-python-client/
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

  RequestsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: requests
      ContentUri: fetch-daily-matches/layer/requests/
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

  AddGcalEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: add-gcal-event/function/
      Description: "add valorant match to google calendar as a event"
      Handler: index.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          OUTBOX_TABLE: !Ref OutboxTable
          GOOGLE_SERVICE_ACCOUNT_ID: !Ref GoogleServiceAccountId
          CALENDAR_ID_APAC: !Ref CalendarIdApac
          CALENDAR_ID_BR_LATAM: !Ref CalendarIdBrLatam
          CALENDAR_ID_EAST_ASIA: !Ref CalendarIdEastAsia
          CALENDAR_ID_EMEA: !Ref CalendarIdEmea
          CALENDAR_ID_NA: !Ref CalendarIdNa
          CALENDAR_ID_INTERNATIONAL: !Ref CalendarIdInternational
      Layers:
        - !Ref GoogleAuthLayer
        - !Ref GoogleApiPythonClientLayer
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt MatchListTable.StreamArn
            BatchSize: 1
            BisectBatchOnFunctionError: true
            Enabled: true
            StartingPosition: TRIM_HORIZON

  AddGCalFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AddGcalEventFunction}
      RetentionInDays: !Ref DaysToRetainLogs

  GetMatchListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-match-list/function/
      Description: "invoke fetch-daily-matches function via SQS queue publishing"
      Handler: index.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 180
      Policies:
        - AmazonSQSFullAccess
      Environment:
        Variables:
          FETCH_DAILY_MATCHES_QUEUE_URL: !Ref FetchDailyMatchesQueue
          BASE_DELAY_SECONDS: 30
          DAYS_TO_GET: !Ref DaysToGet
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression

  GetMatchListFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetMatchListFunction}
      RetentionInDays: !Ref DaysToRetainLogs

  FetchDailyMatchesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fetch-daily-matches/function/
      Description: "fetch daily valorant matches"
      Handler: index.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 900
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          API_DOMAIN_NAME: !Ref APIEndpointDomainName
          MATCHLIST_TABLE: !Ref MatchListTable
      Layers:
        - !Ref RequestsLayer
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt FetchDailyMatchesQueue.Arn
            BatchSize: 1
            ScalingConfig:
              MaximumConcurrency: 2

  FetchDailyMatchesFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${FetchDailyMatchesFunction}
      RetentionInDays: !Ref DaysToRetainLogs

  FetchDailyMatchesQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 10
      VisibilityTimeout: 1000

  MatchListTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties: 
      AttributeDefinitions: 
        - AttributeName: match_id
          AttributeType: N
      BillingMode: PROVISIONED
      DeletionProtectionEnabled: True
      KeySchema: 
        - AttributeName: match_id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  OutboxTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties: 
      AttributeDefinitions: 
        - AttributeName: match_id
          AttributeType: N
        - AttributeName: calendar_id
          AttributeType: S
      BillingMode: PROVISIONED
      DeletionProtectionEnabled: True
      KeySchema: 
        - AttributeName: match_id
          KeyType: HASH
        - AttributeName: calendar_id
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
