AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"
Description: valorant-match-schedule

Parameters:
  APIEndpointDomainName:
    Description: Domain name of API endpoint URL of dima (matches API)
    Type: String
    AllowedPattern: ^([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\.)+[a-zA-Z]{2,}$
    ConstraintDescription: should be appropriate domain format
  GoogleServiceAccountId:
    Type: String
  CalendarIdApac:
    Type: String
  CalendarIdBrLatam:
    Type: String
  CalendarIdEastAsia:
    Type: String
  CalendarIdEmea:
    Type: String
  CalendarIdNa:
    Type: String
  CalendarIdInternational:
    Type: String
  ScheduleExpression:
    Description: schedule expression for the eventbridge event
    Type: String
    Default: rate(3 hours)
  DaysToGet:
    Description: days to get match info starting from today
    Type: Number
    Default: 30
  DaysToRetainLogs:
    Description: days to retain logs in CloudWatch
    Type: Number
    Default: 30

Resources:
  AddGcalEvent:
    Type: AWS::Serverless::Application
    Properties:
      Location: add-gcal-event/template.yaml
      Parameters:
        GoogleServiceAccountId: !Ref GoogleServiceAccountId
        CalendarIdApac: !Ref CalendarIdApac
        CalendarIdBrLatam: !Ref CalendarIdBrLatam
        CalendarIdEastAsia: !Ref CalendarIdEastAsia
        CalendarIdEmea: !Ref CalendarIdEmea
        CalendarIdNa: !Ref CalendarIdNa
        CalendarIdInternational: !Ref CalendarIdInternational
        MatchListTableArn: !GetAtt MatchListTable.StreamArn
        OutboxTableName: !Ref OutboxTable
        DaysToRetainLogs: !Ref DaysToRetainLogs

  GetMatchList:
    Type: AWS::Serverless::Application
    Properties:
      Location: get-match-list/template.yaml
      Parameters:
        ScheduleExpression: !Ref ScheduleExpression
        FetchDailyMatchesQueueUrl: !Ref FetchDailyMatchesQueue
        DaysToGet: !Ref DaysToGet
        DaysToRetainLogs: !Ref DaysToRetainLogs

  FetchDailyMatches:
    Type: AWS::Serverless::Application
    Properties:
      Location: fetch-daily-matches/template.yaml
      Parameters:
        APIEndpointDomainName: !Ref APIEndpointDomainName
        FetchDailyMatchesQueueArn: !GetAtt FetchDailyMatchesQueue.Arn
        MatchListTableName: !Ref MatchListTable
        DaysToRetainLogs: !Ref DaysToRetainLogs

  FetchDailyMatchesQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 10
      VisibilityTimeout: 1000

  MatchListTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties: 
      AttributeDefinitions: 
        - AttributeName: match_id
          AttributeType: N
      BillingMode: PROVISIONED
      DeletionProtectionEnabled: True
      KeySchema: 
        - AttributeName: match_id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  OutboxTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties: 
      AttributeDefinitions: 
        - AttributeName: match_id
          AttributeType: N
        - AttributeName: calendar_id
          AttributeType: S
      BillingMode: PROVISIONED
      DeletionProtectionEnabled: True
      KeySchema: 
        - AttributeName: match_id
          KeyType: HASH
        - AttributeName: calendar_id
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

Outputs:
  MatchListTableName:
    Description: DynamoDB Table for match list
    Value: !Ref MatchListTable
  OutboxTableName:
    Description: DynamoDB Table for outbox(store gcal event status)
    Value: !Ref OutboxTable