AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: valorant-match-schedule - Function fetches match information

Parameters:
  APIEndpointDomainName:
    Description: Domain name of API endpoint URL of dima (matches API)
    Type: String
    AllowedPattern: ^([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\.)+[a-zA-Z]{2,}$
    ConstraintDescription: should be appropriate domain format
  FetchDailyMatchesQueueArn:
    Description: Arn of the SQS Queue to subscribe
    Type: String
  MatchListTableName:
    Description: DynamoDB table name for match list
    Type: String
  DaysToRetainLogs:
    Description: days to retain logs in CloudWatch
    Type: Number
    Default: 30

Resources:
  RequestsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: requests
      ContentUri: layer/requests/
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

  FetchDailyMatchesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/
      Description: "fetch daily valorant matches"
      Handler: index.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 900
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          API_DOMAIN_NAME: !Ref APIEndpointDomainName
          MATCHLIST_TABLE: !Ref MatchListTableName
      Layers:
        - !Ref RequestsLayer
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref FetchDailyMatchesQueueArn
            BatchSize: 1
            ScalingConfig:
              MaximumConcurrency: 2

  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${FetchDailyMatchesFunction}
      RetentionInDays: !Ref DaysToRetainLogs