package application

// CountryToRegionMap is a mapping from country code to region string
var CountryToRegionMap = map[string]string{
	"ar":             "AMERICAS",
	"at":             "EMEA",
	"au":             "PACIFIC",
	"ba":             "EMEA",
	"bd":             "PACIFIC",
	"be":             "EMEA",
	"br":             "AMERICAS",
	"ca":             "AMERICAS",
	"ch":             "EMEA",
	"cl":             "AMERICAS",
	"cn":             "CHINA",
	"co":             "AMERICAS",
	"cz":             "EMEA",
	"de":             "EMEA",
	"dk":             "EMEA",
	"ee":             "EMEA",
	"eg":             "EMEA",
	"es":             "EMEA",
	"fi":             "EMEA",
	"fr":             "EMEA",
	"gb":             "EMEA",
	"gr":             "EMEA",
	"hk":             "PACIFIC",
	"hr":             "EMEA",
	"hu":             "EMEA",
	"id":             "PACIFIC",
	"ie":             "EMEA",
	"il":             "EMEA",
	"in":             "PACIFIC",
	"iq":             "EMEA",
	"is":             "EMEA",
	"it":             "EMEA",
	"jp":             "PACIFIC",
	"kh":             "PACIFIC",
	"kr":             "PACIFIC",
	"kw":             "EMEA",
	"lt":             "EMEA",
	"ma":             "EMEA",
	"me":             "EMEA",
	"mk":             "EMEA",
	"mn":             "PACIFIC",
	"mv":             "PACIFIC",
	"mx":             "AMERICAS",
	"my":             "PACIFIC",
	"no":             "EMEA",
	"pe":             "AMERICAS",
	"ph":             "PACIFIC",
	"pl":             "EMEA",
	"pt":             "EMEA",
	"ro":             "EMEA",
	"rs":             "EMEA",
	"ru":             "EMEA",
	"sa":             "EMEA",
	"se":             "EMEA",
	"sg":             "PACIFIC",
	"si":             "EMEA",
	"th":             "PACIFIC",
	"tr":             "EMEA",
	"tw":             "PACIFIC",
	"ua":             "EMEA",
	"us":             "AMERICAS",
	"vn":             "PACIFIC",
	"asia-pacific":   "PACIFIC",
	"benelux":        "EMEA",
	"cis":            "EMEA",
	"dach":           "EMEA",
	"east-asia":      "PACIFIC",
	"eu":             "EMEA",
	"latam":          "AMERICAS",
	"nordic":         "EMEA",
	"oce":            "PACIFIC",
	"south-asia":     "PACIFIC",
	"southeast-asia": "PACIFIC",
	"usa-ca":         "AMERICAS",
}

var SubAreas = map[string][]string{
	"PACIFIC":  {"Pacific", "East Asia", "KR/JP", "SEA", "Asia Pacific", "Asia-Pacific", "Southeast Asia", "South Asia", "Oceania", "MY/SG"},
	"AMERICAS": {"Americas", "LATAM", "Latin America", "LA-N", "LA-S"},
	"EMEA": {
		"EMEA", "Europe", "Europian", "CIS", "MENA", "Middle East", "Arab", "Arabia",
		"Arabian", "Arabic", "Africa", "NORTH//EAST",
	},
	"CHINA": {"China", "CN", "Chinese"},
}

var Organizers = map[string][]string{
	"PACIFIC":  {"Global Esports"},
	"AMERICAS": {},
	"EMEA":     {"EMG", "ESTAZ", "GLA"},
	"CHINA":    {},
}

var InternationalEvents = []string{
	"Champions Tour 2023: EMEA League",
	"Champions Tour 2023: Pacific League",
	"Champions Tour 2023: Americas League",
	"Champions Tour 2023: Masters Tokyo",
	"Champions Tour 2023: Pacific Last Chance Qualifier",
	"Champions Tour 2023: EMEA Last Chance Qualifier",
	"Champions Tour 2023: Americas Last Chance Qualifier",
	"Valorant Champions 2023",
	"Game Changers 2023 Championship: São Paulo",
	"Red Bull Home Ground #4",
	"Champions Tour 2024: Americas Kickoff",
	"Champions Tour 2024: Pacific Kickoff",
	"Champions Tour 2024: EMEA Kickoff",
	"Champions Tour 2024: China Kickoff",
	"Champions Tour 2024: Masters Madrid",
	"Champions Tour 2024: Americas Stage 1",
	"Champions Tour 2024: EMEA Stage 1",
	"Champions Tour 2024: Pacific Stage 1",
	"Champions Tour 2024: China Stage 1",
	"Champions Tour 2024: Masters Shanghai",
	"Champions Tour 2024: Americas Stage 2",
	"Champions Tour 2024: EMEA Stage 2",
	"Champions Tour 2024: Pacific Stage 2",
	"Champions Tour 2024: China Stage 2",
	"Valorant Champions 2024",
	"Game Changers 2024 Championship: Berlin",
	"Red Bull Home Ground #5",
	"Champions Tour 2025: Americas Kickoff",
	"Champions Tour 2025: Pacific Kickoff",
	"Champions Tour 2025: EMEA Kickoff",
	"Champions Tour 2025: China Kickoff",
	"VCT 2025: Americas Kickoff",
	"VCT 2025: Pacific Kickoff",
	"VCT 2025: EMEA Kickoff",
	"VCT 2025: China Kickoff",
	"Champions Tour 2025: Masters Bangkok",
	"Valorant Masters Bangkok 2025",
	"Champions Tour 2025: Masters Toronto",
	"Valorant Masters Toronto 2025",
	"Champions Tour 2025: China Stage 1",
	"Champions Tour 2025: Americas Stage 1",
	"Champions Tour 2025: EMEA Stage 1",
	"Champions Tour 2025: Pacific Stage 1",
	"VCT 2025: China Stage 1",
	"VCT 2025: Americas Stage 1",
	"VCT 2025: EMEA Stage 1",
	"VCT 2025: Pacific Stage 1",
	"VCT 2025: China Stage 2",
	"VCT 2025: Americas Stage 2",
	"VCT 2025: EMEA Stage 2",
	"VCT 2025: Pacific Stage 2",
	"Valorant Champions 2025",
	"Esports World Cup 2025",
}
