on:
  workflow_dispatch:
  push:
    branches:
      - v2
    paths-ignore:
      - ".github/workflows/*"
      - "**.md"
      - "website/**"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          cache: true
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true
      - name: Build Go functions
        run: mise build
      - name: Deploy SAM application
        run: |
          sam deploy \
            --config-file samconfig.toml \
            --config-env production \
            --force-upload \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
